name = "hytapi"
main = "./build/dev/javascript/hytapi/index.js"
compatibility_date = "2025-06-17"

[[d1_databases]]
binding = "hytapi_prod"
database_name = "hytapi-prod"
database_id = "5ac863e0-df1b-4aec-a52d-01f138ddfd66"

